name: OCC Memos → Google Calendar (KST 09:00 collect, 09:30 insert)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Collect OCC memos (future-only, exclude FLEX)
        run: |
          echo "여기에 occ_memo_daily_slack.py 호출 부분을 붙여넣으세요."
